server:
  port: 8889

spring:
  application:
    name: SparkTest

logging:
  level:
    root: INFO
    org.apache.spark: WARN
    org.sparkproject.jetty.server.handler.ContextHandler: WARN

# springdoc-openapi项目配置
springdoc:
  # 配置Swagger UI的访问路径和排序方式
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI的访问路径
    tags-sorter: alpha      # 按字母顺序排序标签
    operations-sorter: alpha  # 按字母顺序排序操作
  # 配置API文档的访问路径
  api-docs:
    path: /v3/api-docs  # API文档的访问路径
  # 配置API分组，用于组织和管理API, 作用于/v3/api-docs访问地址
  group-configs:
    - group: 'spark'   # API分组名称
      paths-to-match: '/**'  # 匹配所有路径
      display-name: 'spark下全部接口'
      packages-to-scan: com.example.sparktest.spark # 扫描的包，用于自动发现API

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-dynamic-parameter: true # 动态请求参数
  basic:
    enable: false